<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dictionary['SalesTargets'] = array(
    'table' => 'sales_targets',
    'audited' => true,
    'fields' => array(
        'target_type' => array(
            'name' => 'target_type',
            'vname' => 'LBL_TARGET_TYPE',
            'type' => 'enum',
            'options' => 'sales_target_type_list',
            'len' => 50,
            'required' => true,
            'default' => 'bdm',
        ),
        'target_user_id' => array(
            'name' => 'target_user_id',
            'vname' => 'LBL_TARGET_USER',
            'type' => 'id',
            'reportable' => false,
        ),
        'target_user_name' => array(
            'name' => 'target_user_name',
            'rname' => 'name',
            'id_name' => 'target_user_id',
            'vname' => 'LBL_TARGET_USER',
            'type' => 'relate',
            'table' => 'users',
            'module' => 'Users',
            'dbType' => 'varchar',
            'link' => 'target_user_link',
            'len' => 255,
            'source' => 'non-db',
        ),
        'target_user_link' => array(
            'name' => 'target_user_link',
            'type' => 'link',
            'relationship' => 'sales_targets_target_user',
            'vname' => 'LBL_TARGET_USER',
            'link_type' => 'one',
            'module' => 'Users',
            'bean_name' => 'User',
            'source' => 'non-db',
        ),
        'team_id' => array(
            'name' => 'team_id',
            'vname' => 'LBL_TEAM',
            'type' => 'id',
            'reportable' => false,
        ),
        'funnel_type' => array(
            'name' => 'funnel_type',
            'vname' => 'LBL_FUNNEL_TYPE',
            'type' => 'enum',
            'options' => 'funnel_type_list',
            'len' => 100,
        ),
        'period_type' => array(
            'name' => 'period_type',
            'vname' => 'LBL_PERIOD_TYPE',
            'type' => 'enum',
            'options' => 'sales_period_type_list',
            'len' => 50,
            'default' => 'monthly',
        ),
        'period_year' => array(
            'name' => 'period_year',
            'vname' => 'LBL_PERIOD_YEAR',
            'type' => 'int',
            'len' => 4,
            'required' => true,
        ),
        'period_month' => array(
            'name' => 'period_month',
            'vname' => 'LBL_PERIOD_MONTH',
            'type' => 'int',
            'len' => 2,
        ),
        'period_quarter' => array(
            'name' => 'period_quarter',
            'vname' => 'LBL_PERIOD_QUARTER',
            'type' => 'int',
            'len' => 1,
        ),
        'revenue_target' => array(
            'name' => 'revenue_target',
            'vname' => 'LBL_REVENUE_TARGET',
            'type' => 'currency',
            'dbType' => 'decimal',
            'len' => '26,6',
            'default' => 0,
        ),
        'revenue_actual' => array(
            'name' => 'revenue_actual',
            'vname' => 'LBL_REVENUE_ACTUAL',
            'type' => 'currency',
            'dbType' => 'decimal',
            'len' => '26,6',
            'default' => 0,
        ),
        'demos_target' => array(
            'name' => 'demos_target',
            'vname' => 'LBL_DEMOS_TARGET',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
        ),
        'demos_actual' => array(
            'name' => 'demos_actual',
            'vname' => 'LBL_DEMOS_ACTUAL',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
        ),
        'leads_target' => array(
            'name' => 'leads_target',
            'vname' => 'LBL_LEADS_TARGET',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
        ),
        'leads_actual' => array(
            'name' => 'leads_actual',
            'vname' => 'LBL_LEADS_ACTUAL',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
        ),
        'calls_target' => array(
            'name' => 'calls_target',
            'vname' => 'LBL_CALLS_TARGET',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
        ),
        'calls_actual' => array(
            'name' => 'calls_actual',
            'vname' => 'LBL_CALLS_ACTUAL',
            'type' => 'int',
            'len' => 11,
            'default' => 0,
        ),
        'commission_rate' => array(
            'name' => 'commission_rate',
            'vname' => 'LBL_COMMISSION_RATE',
            'type' => 'decimal',
            'len' => '5,2',
            'default' => 5.00,
            'comment' => 'Commission rate percentage',
        ),
        'commission_earned' => array(
            'name' => 'commission_earned',
            'vname' => 'LBL_COMMISSION_EARNED',
            'type' => 'currency',
            'dbType' => 'decimal',
            'len' => '26,6',
            'default' => 0,
        ),
        'commission_paid' => array(
            'name' => 'commission_paid',
            'vname' => 'LBL_COMMISSION_PAID',
            'type' => 'bool',
            'default' => 0,
        ),
    ),
    'relationships' => array(
        'sales_targets_target_user' => array(
            'lhs_module' => 'Users',
            'lhs_table' => 'users',
            'lhs_key' => 'id',
            'rhs_module' => 'SalesTargets',
            'rhs_table' => 'sales_targets',
            'rhs_key' => 'target_user_id',
            'relationship_type' => 'one-to-many',
        ),
    ),
    'indices' => array(
        array(
            'name' => 'idx_target_user',
            'type' => 'index',
            'fields' => array('target_user_id'),
        ),
        array(
            'name' => 'idx_team',
            'type' => 'index',
            'fields' => array('team_id'),
        ),
        array(
            'name' => 'idx_period',
            'type' => 'index',
            'fields' => array('period_year', 'period_month', 'period_quarter'),
        ),
        array(
            'name' => 'idx_funnel',
            'type' => 'index',
            'fields' => array('funnel_type'),
        ),
    ),
);

VardefManager::createVardef('SalesTargets', 'SalesTargets', array('basic', 'assignable'));
